.PHONY: dev build start lint format lighthouse docker-build docker-run

dev:
	npm run dev

build:
	npm run build

start:
	npm run start

lint:
	npm run lint

format:
	npm run format

lighthouse:
	npm run lighthouse

docker-build:
	docker build -t __PROJECT_NAME__ .

docker-run:
	docker run -p 3000:3000 __PROJECT_NAME__
